Merging code of DSA-35 to develop branch
aravindsamala01/DSA-Training pull request #9
Opened 2024-07-16 12:09 UTC by Umarfarook1

transfering code to develop branch

2024-07-16 17:23 UTC, ganeshyevle commented on DSA_Training/MinMax.py
> +def find_min_max(nums, low, high):
please add Comments here

2024-07-16 17:24 UTC, ganeshyevle commented on DSA_Training/MinMax.py
> +
please add comment here

2024-07-16 17:25 UTC, ganeshyevle requested changes
Please Add proper Comments in your code

2024-07-17 08:37 UTC, Umarfarook1 commented on DSA_Training/MinMax.py
> +def find_min_max(nums, low, high):
Done

2024-07-17 08:38 UTC, Umarfarook1 commented on DSA_Training/MinMax.py
> +
done

2024-07-17 08:39 UTC, Umarfarook1 commented
> Please Add proper Comments in your code

Done

2024-07-17 09:04 UTC, ganeshyevle approved these changes

2024-07-17 09:05 UTC, ganeshyevle commented
Done Approved

2024-07-17 09:27 UTC, merged